Allowing doctrine-extensions v3
stof/StofDoctrineExtensionsBundle pull request #415
Opened 2020-09-15 15:21 UTC by weaverryan

Fixes #413 and fixes #414 

Right now, people are having trouble installing this bundle because they are already locked at `doctrine/common` 3 or `doctrine/persistence` 2. You CAN work around this - #413. 

However, this will be fixed in  gedmo/doctrine-extensions v3, which is not installed yet. This will get the tests running so we can make sure all is good. Once gedmo/doctrine-extensions v3 is released, we can change the constraint to `^2.3.4 || ^3.0` and tag :).

Thanks!

2020-09-15 16:12 UTC, weaverryan commented
Awesome! Tests pass - I verified that the matrix IS testing but v2 and v3, and both are passing :)

2020-09-20 11:08 UTC, mindaugasw commented
For anyone wondering how to install this PR until it will get merged:

Add to composer.json:
```
"require": {
   "stof/doctrine-extensions-bundle": "1.5.x-dev"
},
"repositories": [
        {
            "url": "git@github.com:weaverryan/StofDoctrineExtensionsBundle.git",
            "type": "git",
            "reference": "allow-extensions-3"
        }
    ],
```
Run `composer update`

Took me quite some time to figure this out, maybe will help someone else.

2020-09-24 04:42 UTC, rimas-kudelis commented
Hi! Now that extensions 3.0 has been released, I hope you guys can go ahead ant tag a new version as well? :)

2020-09-25 10:16 UTC, Jmoati commented
> For anyone wondering how to install this PR until it will get merged:
> 
> Add to composer.json:
> 
> ```
> "require": {
>    "stof/doctrine-extensions-bundle": "1.5.x-dev"
> },
> "repositories": [
>         {
>             "url": "git@github.com:weaverryan/StofDoctrineExtensionsBundle.git",
>             "type": "git",
>             "reference": "allow-extensions-3"
>         }
>     ],
> ```
> 
> Run `composer update`
> 
> Took me quite some time to figure this out, maybe will help someone else.

Too Hard !

Why not just override the constaint in your project's composer.json with this : 

```
    "replace": {
         ...
        "gedmo/doctrine-extensions": "*"
    },

```

It's just work ;)

2020-09-25 19:24 UTC, stof requested changes

2020-09-25 19:24 UTC, stof commented on composer.json
> +        "gedmo/doctrine-extensions": "^2.3.4 || ^3.0.0-beta2@beta"
@weaverryan please change the constraint to `^2.3.4 || ^3.0.0` as 3.0 is now released.

2020-09-30 12:09 UTC, stof commented
Closing in favor of #416

2020-09-30 12:09 UTC, closed without merging